steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner#3bdf15862f4ceb38dbc41ca66ed214e1d67d0dec:
          # This will create one job per file
          watch:
            - path: benchmarks/.*\.jmd
          path_processor: per-file
          target: .buildkite/rebuild_model.yml
          target_type: template
      - staticfloat/forerunner:
          # This will create one job overall, throwing all path information away
          watch:
            - path: src/*.*.jl
            - path: .*\\.toml
          target: .buildkite/test_sciml.yml