steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner#0c78044b02ced95d8b9ca6fda7883fba45862fd2:
          # This will create one job overall, throwing all path information away
          watch:
            - path: src/*.*.jl
            - path: .*\\.toml
          target: .buildkite/test_sciml.yml