steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner#0c78044b02ced95d8b9ca6fda7883fba45862fd2:
          # This will create one job per project
          watch:
            - path: benchmarks/.*\.jmd
            - path: benchmarks/.*\.toml
          path_processor: .buildkite/path_processors/project-coalescing
          target: .buildkite/run_benchmark.yml
          target_type: template
      - staticfloat/forerunner#0c78044b02ced95d8b9ca6fda7883fba45862fd2:
          # This will create one job overall, throwing all path information away
          watch:
            - path: src/*.*.jl
            - path: .*\\.toml
          target: .buildkite/test_sciml.yml
    agents:
      queue: "benchmark"
    # Only do this work if this is a pull request
    if: "build.pull_request.id != null"

  - command: .buildkite/find_previous_build.sh
    if: "build.pull_request.id == null"
  # - label: "Deploy previous build"
  #   if: "branch == master"
  #   env:
  #     SECRET_BUILDKITE_API_TOKEN: "SVblSi8mxgKNU8uXsw98zen+7v94owKFI2QUUnKUcg145rO5VXs8daxFzbNfVTEY4gIXm1xE58I9QAlAijKxquSCfgC3ngnKyK6JpBQ6pm0rIrWsANiai1NymrJ4gDE03z8N/nwRpmpg6YfhIxvweMTGUirW1XEbGm/ueATLL1F1GPe/XDSU5O/SaAsF4vaqFNFcCUZ6+8EqYtZxvFBcPpqacpMUG0vSGHQpeLiiKbiPxiisS2CJ+e3loUJZPt40kACHx1sVJZ29YdvQ5FD/Cb/nIfO8F//5oZnct9ahUiuZVpclKBBPJdh1og53vYsTxMjMU5c1s6AgF6TKrg6uMA==;U2FsdGVkX1+R5ly/HoiS8IcDJ77njQ3J/pAFy9z6OuVqoDc+XtsIaLYe+YcitCfrS/lSciiU+Ym/JWfOjdG47w=="
