# This is a pipeline that rebuilds a model, then uploads the resultant
# model files and .PDF report as (buildkite, not Julia) artifacts.

steps:
  - label: ":hammer: {MODEL}"
    plugins:
      # Install Julia
      - JuliaCI/julia#2ec318d9e84fd5b6a402d926e7451e8b57b77d6c:
          version: 1.6
    timeout_in_minutes: 60
    commands:
      # Instantiate current project
      - echo "--- Instantiate Project"
      - julia --project=. .buildkite/commands/instantiate.jl
      # Reuild the given model
      - echo "+++ Build {MODEL}"
      - julia --project=. .buildkite/commands/rebuild_model.jl {MODEL}
      - MODEL_NAME=${MODEL%.*}
    artifact_paths:
      # Upload .html
      - "html/${MODEL_NAME}*.html"
      # Upload markdown
      - "markdown/${MODEL_NAME}*.md"
      # Upload notebook
      - "notebook/${MODEL_NAME}*.ipynb"
      # Upload .pdf files
      - "pdf/${MODEL_NAME}.pdf"
      # Upload Julia script
      - "script/${MODEL_NAME}*.jl"