# This is a pipeline that rebuilds a model, then uploads the resultant
# model files and .PDF and other reports as (buildkite, not Julia) artifacts.

steps:
  - label: ":hammer: {PATH}"
      # Install Julia
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
    timeout_in_minutes: 60
    commands:
      # Rebuild the given model
      - echo "+++ Build {PATH}"
      - julia --project=. .buildkite/commands/rebuild_models.jl {PATH}
    # artifact_paths:
      # Upload .html
      # - "html/{PATH_NAME}*.html"
      # Upload markdown
      #- "markdown/{PATH_NAME}*.md"
      # Upload notebook
      #- "notebook/{PATH_NAME}*.ipynb"
      # Upload .pdf files
      # - "pdf/{PATH_NAME}.pdf"
      # # Upload Julia script
      # - "script/{PATH_NAME}*.jl"