steps:
  - label: ":julia: Run tests on 1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
      - JuliaCI/julia-test#v1:
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120
    artifact_paths:
       # Upload .html
      - "html/*/*.html"
      # Upload markdown
      - "markdown/*/*.md"
      # Upload notebook
      - "notebook/*/*.ipynb"
      # Upload .pdf files
      - "pdf/*/*.pdf"
      # Upload Julia script
      - "script/*/*.jl"
    agents:
      queue: "benchmark"
